name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -project ./CombineExample.xcodeproj -scheme CombineExample -configuration Release build -allowProvisioningUpdates
    - name: Run tests
      run: swift test -v
